- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy Roboshop Configuration
  ansible.builtin.copy:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: clean old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create App Directiory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download And extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Create prometheus exporter directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory


- name: Download Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: Copy Nginx prometheus exporter service
  ansible.builtin.copy:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx-exporter.service

- name: Restart prometheus exporter service
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    enabled: yes
