- name: copy prometheus configuration
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy alert file
  ansible.builtin.copy:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name : Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted