- name: Copy MongoDB Yum Repo File
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Download DocumentDB Pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: Load Schema
  ansible.builtin.shell: mongo --host mongodb-dev.tirupathib74.online </app/schema/{{component}}.js
